name: Build Initrd

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-initrd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Initrd
        run: make all
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: core
          path: ./build/core.gz