name: Compile

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-initrd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Initrd
        run: make BUILD=/tmp/initrd/build/ build